services:

    wcf.authentication_response_no_action:
        class: stepotronic\WcfToSymfonyBridgeBundle\Security\Guard\AuthenticationResponseStrategy\NoAction

    wcf.authentication_redirect_to_login_route:
        class: stepotronic\WcfToSymfonyBridgeBundle\Security\Guard\AuthenticationResponseStrategy\RedirectToRoute
        arguments:
            - "@router"
            - "security_login"

    wcf.authentication_redirect_to_wcf_login_url:
        class: stepotronic\WcfToSymfonyBridgeBundle\Security\Guard\AuthenticationResponseStrategy\RedirectToUrl
        arguments:
            - "/index.php/Login"

    wcf.cookie_hash_authenticator:
        class: stepotronic\WcfToSymfonyBridgeBundle\Security\Guard\CookieHashAuthenticator
        arguments:
            - "@wcf.authentication_redirect_to_login_route"
            - "@wcf.authentication_response_no_action"
            - "@wcf.authentication_redirect_to_login_route"
            - "%wcf_to_symfony_bridge.cookie_prefix%"

    wcf.form_login_authenticator:
        class: stepotronic\WcfToSymfonyBridgeBundle\Security\Guard\FormLoginAuthenticator
        arguments:
            - "@wcf.repository.user_repository"
            - "@router"
            - "@security.password_encoder"
            - %wcf_to_symfony_bridge.default_success_route%

    wcf.repository.user_repository:
        class: stepotronic\WcfToSymfonyBridgeBundle\Repository\WcfUserRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - WcfToSymfonyBridgeBundle:WcfUser

    wcf.password_encoder:
        class: stepotronic\WcfToSymfonyBridgeBundle\Security\Core\Encoder\WcfPasswordEncoder

    wcf.tableprefix_subscriber:
        class: stepotronic\WcfToSymfonyBridgeBundle\Subscriber\WcfTablePrefixSubscriber
        arguments:
            - %wcf_to_symfony_bridge.table_prefix%
            - %wcf_to_symfony_bridge.prefixed_entity_classes%
        tags:
            - { name: doctrine.event_subscriber }        